apiVersion: v1
kind: Service
metadata:
  name: hivemq-headless
  namespace: hivemq
  labels:
    app: hivemq
spec:
  clusterIP: None
  selector:
    app: hivemq
  ports:
    - name: mqtt
      port: 1883
    - name: mqtts
      port: 8883