apiVersion: v1
kind: Service
metadata:
  name: hivemq
  namespace: hivemq
  labels:
    app: hivemq
spec:
  type: ClusterIP
  selector:
    app: hivemq
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: mqtts
      port: 8883
      targetPort: 8883
    - name: admin
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9399
      targetPort: 9399